#!/usr/bin/env node
/* =============================================================================
   build-single.js - bundle the site into one self-contained .html file.

   Same code, one file: inlines the stylesheet, every script, and the favicon so
   the result can be emailed, dropped on a USB stick, or double-clicked with no
   checkout and no server. Run it after changing anything under css/ or js/:

       node tools/build-single.js

   The modular files under css/ and js/ remain the source of truth; this is a
   derived artefact, never edited by hand.
   ========================================================================== */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

let html = read('index.html');

// Guard against the bundler silently producing a broken file.
const expectScripts = (html.match(/<script src="[^"]+"><\/script>/g) || []).length;
if (expectScripts === 0) throw new Error('No <script src> tags found - has index.html changed shape?');

// 1. Stylesheet -> inline <style>
html = html.replace(
  /<link rel="stylesheet" href="(css\/[^"]+)">/,
  (_, href) => '<style>\n/* ' + href + ' */\n' + read(href) + '\n</style>'
);

// 2. Favicon -> data URI (so the tab icon survives with no sibling files)
const favicon = read('assets/favicon.svg');
html = html.replace(
  /<link rel="icon" href="[^"]+" type="image\/svg\+xml">/,
  '<link rel="icon" type="image/svg+xml" href="data:image/svg+xml;base64,' +
    Buffer.from(favicon, 'utf8').toString('base64') + '">'
);

// 3. Scripts -> inline, in the original order
let inlined = 0;
html = html.replace(/<script src="(js\/[^"]+)"><\/script>/g, (_, src) => {
  inlined++;
  const code = read(src);
  // A closing tag inside a string literal would end the inline block early.
  if (/<\/script/i.test(code)) throw new Error('Cannot inline ' + src + ': contains a closing script tag');
  return '<script>\n/* ' + src + ' */\n' + code + '\n</script>';
});
if (inlined !== expectScripts) {
  throw new Error('Inlined ' + inlined + ' of ' + expectScripts + ' scripts');
}

html = html.replace(
  '<title>',
  '<!-- Built by tools/build-single.js from the files under css/ and js/.\n' +
  '     Do not edit this file directly - edit the sources and rebuild. -->\n<title>'
);

const out = path.join(root, 'volcano-studio.html');
fs.writeFileSync(out, html);
const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
console.log('Wrote volcano-studio.html (' + kb + ' KB, ' + inlined + ' scripts + 1 stylesheet inlined)');
